name: Consulta API a cada 15 minutos

on:
  schedule:
    # Executar a cada 15 minutos
    - cron: '*/15 * * * *'
  workflow_dispatch: # Permite execução manual via interface do GitHub

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checar o código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Executar o script
        run: python Distrib_GAM_API_Pedidos_v_4.py

      - name: Commit e Push do Log
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add execucoes.log
          git commit -m "Atualizando log de execução"
          git push
        continue-on-error: true